#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 2001 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../LICENSE.   #
#                                                                       #
#########################################################################

# $Id: Makefile.nt 8477 2007-11-06 15:16:56Z frisch $

LIBNAME=graphics
COBJS=open.$(O) draw.$(O) events.$(O) dib.$(O)
CAMLOBJS=graphics.cmo
WIN32LIBS=$(call SYSLIB,kernel32) $(call SYSLIB,gdi32) $(call SYSLIB,user32)
LINKOPTS=-cclib "\"$(WIN32LIBS)\""
LDOPTS=-ldopt "$(WIN32LIBS)"

include ../Makefile.nt

graphics.ml: ../graph/graphics.ml
	cp ../graph/graphics.ml graphics.ml
graphics.mli: ../graph/graphics.mli
	cp ../graph/graphics.mli graphics.mli

depend:

graphics.cmo: graphics.cmi
graphics.cmx: graphics.cmi
draw.$(O): libgraph.h
open.$(O): libgraph.h
