FROM ocaml/opam:debian-stable_ocaml-4.03.0
RUN cd /home/opam/opam-repository && git pull origin master && opam update
RUN opam remote add mirage-dev https://github.com/mirage/mirage-dev.git
RUN opam pin add -n odig https://github.com/dbuenzli/odig.git
RUN opam depext -uivy -j 2 odig 
RUN opam depext -uivj 3 \
  alcotest \
  angstrom \
  arp \
  channel \
  charrua-core \
  cohttp \
  conduit \
  core_kernel \
  cow \
  cowabloga \
  crunch \
  cstruct \
  ctypes \
  ctypes-foreign \
  datakit-client \
  datakit-github \
  datakit-ci \
  dns \
  dockerfile \
  ezxmlm \
  git \
  git-mirage \
  git-unix \
  github \
  hex \
  hvsock \
  integers \
  ipaddr \
  irmin \
  irmin-watcher \
  lwt \
  magic-mime \
  merlin \
  mirage \
  mirage-block-unix \
  mirage-block-xen \
  mirage-btrees \
  mirage-clock-unix \
  mirage-clock-xen \
  mirage-console \
  mirage-dns \
  mirage-entropy \
  mirage-flow \
  mirage-fs-unix \
  mirage-http \
  mirage-net-unix \
  mirage-net-xen \
  mirage-unix \
  mirage-vnetif \
  mirage-xen \
  obytelib \
  ocamlclean \
  opam-file-format \
  parse-argv \
  pcap-format \
  ppx_expect \
  qcow-format \
  re \
  scrypt-kdf \
  session \
  shared-memory-ring \
  tcpip \
  tls \
  tlstunnel \
  tyre \
  topkg-care \
  tyxml-ppx \
  uri \
  vchan \
  vhd-format \
  webmachine \
  websocket \
  xen-evtchn \
  xen-gnt \
  xenctrl \
  yojson
RUN opam config exec -- odig ocamldoc
RUN opam pin add -n octavius git://github.com/ocaml-doc/octavius
RUN opam pin add -n doc-ock git://github.com/ocaml-doc/doc-ock
RUN opam pin add -n doc-ock-xml git://github.com/ocaml-doc/doc-ock-xml
RUN opam pin add -n doc-ock-html git://github.com/ocaml-doc/doc-ock-html
RUN opam pin add -n odoc git://github.com/ocaml-doc/odoc
RUN opam depext -uivy -j 2 odoc
RUN opam config exec -- odig odoc
RUN ln -s /home/opam/.opam/4.03.0/var/cache/odig/odoc /home/opam/.opam/4.03.0/var/cache/odig/ocamldoc/odoc
EXPOSE 8080
ENTRYPOINT opam config exec -- cohttp-server-lwt /home/opam/.opam/4.03.0/var/cache/odig/ocamldoc
