#!/bin/sh
# $Id: runocamldoc 10443 2010-05-20 09:44:25Z doligez $

case "$1" in
  true) shift
        exec ../boot/ocamlrun  -I ../otherlibs/unix -I ../otherlibs/str \
             ./ocamldoc "$@"
        ;;
     *) shift
        exec ./ocamldoc "$@"
        ;;
esac
