ROOTDIR=../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=lwt
TARGET=browser
TARGET_MLI=browser.mli
SOURCES= activations.ml clock.ml console.ml time.ml websocket.ml main.ml

WITH_SYNTAX=yes
NO_NATIVE_CODE=yes
USE_PACK=yes
include ../Makefile.common

