ROOTDIR=../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=lwt
TARGET=oS
TARGET_MLI=oS.mli
SOURCES= console.ml activations.ml clock.ml time.ml websocket.ml main.ml

WITH_SYNTAX=yes
NO_NATIVE_CODE=yes
USE_PACK=yes
include ../Makefile.common

