OCAMLMAKEFILE=OCamlMakefile

SOURCES=lwip_stubs.c lwip.ml main.ml
RESULT=lwip
INCDIRS = ../lwip/src/include/ ../lwip/src/include/ipv4 ../lib_test/include ../lib_test 
PACKS=lwt lwt.unix lwt.syntax
PREDS=camlp4o
LIBDIRS=../lib_test
CLIBS=lwip4
CFLAGS=-Wall -pedantic
RESULT=echop

include $(OCAMLMAKEFILE)
