# Copyright (C) 2002 by Red Hat, Incorporated. All rights reserved.
#
# Permission to use, copy, modify, and distribute this software
# is freely granted, provided that this notice is preserved.
#

global host_triplet target_triplet

load_lib passfail.exp

set exclude_list {
}

verbose $host_triplet
verbose $target_triplet

if [string match "i\[3456\]86-pc-linux-gnu" $target_triplet] then {
  newlib_pass_fail_all -x $exclude_list
}
