ROOTDIR=../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=lwt mpl
TARGET=unix
TARGET_MLI=unix.mli
SOURCES=console.ml clock.ml activations.ml main.ml ethif.ml time.ml

WITH_SYNTAX=yes
USE_PACK=yes
NO_JS_CODE=yes
include ../Makefile.common
