ROOTDIR=../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=lwt mpl mlnet io
TARGET=oS
TARGET_MLI=oS.mli
SOURCES=console.ml clock.ml activations.ml main.ml ethif.ml time.ml channel.ml 

WITH_SYNTAX=yes
USE_PACK=yes
NO_JS_CODE=yes
include ../Makefile.common
