.PHONY: all
all:
	cd stdlib && $(MAKE)
	cd lwt && $(MAKE)
	cd xen && $(MAKE)
	cd mpl && $(MAKE)
	cd mlnet && $(MAKE)

.PHONY: clean
clean:
	cd stdlib && $(MAKE) clean
	cd lwt && $(MAKE) clean
	cd xen && $(MAKE) clean
	cd mpl && $(MAKE) clean
	cd mlnet && $(MAKE) clean

.PHONY: install
install:
	@ :
