ifeq ($(WITH_SYNTAX),yes)
SYNTAX=-pp 'camlp4o -I $(ROOTDIR)/syntax pa_mirage.cma'
else
SYNTAX=
endif

.mldeps: *.ml *.mli
	$(OCAMLDSORT) $(SYNTAX) -mli *.ml *.mli > $@

.cmxdeps: .mldeps
	$(OCAMLDSORT) $(SYNTAX) -opt *.ml > $@

.cmjsdeps: .cmxdeps
	sed -e 's/\.cmx/.cmjs/g' < $< > $@

%.cmxa: %.cmx
	$(OCAMLOPT) -a -o $@ $^

%.cmjsa: %.cmjs
	$(OCAMLJS) -a -o $@ $^

.PHONY: clean
clean:
	rm -f *.cmx *.cmo *.o *.cmi *.cmxa .mldeps .cmxdeps *.cmjs *.cmjsa

