
/*
 * sanity checks for generated foreign headers:
 *  - verify struct sizes
 *
 * generated by %s -- DO NOT EDIT
 */
#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <inttypes.h>
#include "x86_32.h"
#include "x86_64.h"
#include "ia64.h"
int main(int argc, char *argv[])
{
	printf("\n");printf("%-25s |", "structs");
	printf("%8s", "x86_32");
	printf("%8s", "x86_64");
	printf("%8s", "ia64");
	printf("\n");	printf("\n");	printf("%-25s |", "start_info");
#ifdef x86_32_has_no_start_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct start_info_x86_32));
#endif
#ifdef x86_64_has_no_start_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct start_info_x86_64));
#endif
#ifdef ia64_has_no_start_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct start_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "trap_info");
#ifdef x86_32_has_no_trap_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct trap_info_x86_32));
#endif
#ifdef x86_64_has_no_trap_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct trap_info_x86_64));
#endif
#ifdef ia64_has_no_trap_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct trap_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "pt_fpreg");
#ifdef x86_32_has_no_pt_fpreg
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct pt_fpreg_x86_32));
#endif
#ifdef x86_64_has_no_pt_fpreg
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct pt_fpreg_x86_64));
#endif
#ifdef ia64_has_no_pt_fpreg
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct pt_fpreg_ia64));
#endif
	printf("\n");

	printf("%-25s |", "cpu_user_regs");
#ifdef x86_32_has_no_cpu_user_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct cpu_user_regs_x86_32));
#endif
#ifdef x86_64_has_no_cpu_user_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct cpu_user_regs_x86_64));
#endif
#ifdef ia64_has_no_cpu_user_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct cpu_user_regs_ia64));
#endif
	printf("\n");

	printf("%-25s |", "xen_ia64_boot_param");
#ifdef x86_32_has_no_xen_ia64_boot_param
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct xen_ia64_boot_param_x86_32));
#endif
#ifdef x86_64_has_no_xen_ia64_boot_param
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct xen_ia64_boot_param_x86_64));
#endif
#ifdef ia64_has_no_xen_ia64_boot_param
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct xen_ia64_boot_param_ia64));
#endif
	printf("\n");

	printf("%-25s |", "ia64_tr_entry");
#ifdef x86_32_has_no_ia64_tr_entry
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct ia64_tr_entry_x86_32));
#endif
#ifdef x86_64_has_no_ia64_tr_entry
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct ia64_tr_entry_x86_64));
#endif
#ifdef ia64_has_no_ia64_tr_entry
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct ia64_tr_entry_ia64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_tr_regs");
#ifdef x86_32_has_no_vcpu_tr_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_tr_regs_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_tr_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_tr_regs_x86_64));
#endif
#ifdef ia64_has_no_vcpu_tr_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_tr_regs_ia64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_guest_context_regs");
#ifdef x86_32_has_no_vcpu_guest_context_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_regs_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_guest_context_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_regs_x86_64));
#endif
#ifdef ia64_has_no_vcpu_guest_context_regs
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_regs_ia64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_guest_context");
#ifdef x86_32_has_no_vcpu_guest_context
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_guest_context
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_x86_64));
#endif
#ifdef ia64_has_no_vcpu_guest_context
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_guest_context_ia64));
#endif
	printf("\n");

	printf("%-25s |", "arch_vcpu_info");
#ifdef x86_32_has_no_arch_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_x86_32));
#endif
#ifdef x86_64_has_no_arch_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_x86_64));
#endif
#ifdef ia64_has_no_arch_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_vcpu_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_time_info");
#ifdef x86_32_has_no_vcpu_time_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_time_info_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_time_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_time_info_x86_64));
#endif
#ifdef ia64_has_no_vcpu_time_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_time_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "vcpu_info");
#ifdef x86_32_has_no_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_info_x86_32));
#endif
#ifdef x86_64_has_no_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_info_x86_64));
#endif
#ifdef ia64_has_no_vcpu_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct vcpu_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "arch_shared_info");
#ifdef x86_32_has_no_arch_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_shared_info_x86_32));
#endif
#ifdef x86_64_has_no_arch_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_shared_info_x86_64));
#endif
#ifdef ia64_has_no_arch_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct arch_shared_info_ia64));
#endif
	printf("\n");

	printf("%-25s |", "shared_info");
#ifdef x86_32_has_no_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct shared_info_x86_32));
#endif
#ifdef x86_64_has_no_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct shared_info_x86_64));
#endif
#ifdef ia64_has_no_shared_info
	printf("%8s", "-");
#else
	printf("%8zd", sizeof(struct shared_info_ia64));
#endif
	printf("\n");

	printf("\n");
	exit(0);
}
