#!/bin/sh
# $Id: runocamldoc 5029 2002-07-23 14:12:03Z doligez $

case "$1" in
  true) shift
        exec ../boot/ocamlrun  -I ../otherlibs/unix -I ../otherlibs/str \
             ./ocamldoc "$@"
        ;;
     *) shift
        exec ./ocamldoc "$@"
        ;;
esac
