ROOTDIR=../../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=
TARGET=oS
SOURCES= console.ml activations.ml clock.ml time.ml main.ml

WITH_SYNTAX=yes
NO_NATIVE_CODE=yes
USE_PACK=yes
include ../../Makefile.common

