ROOTDIR=../../../
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=
TARGET=oS
SOURCES=console.ml clock.ml activations.ml time.mli time.ml main.mli main.ml hw_page.mli hw_page.ml ethif.ml

WITH_SYNTAX=yes
USE_PACK=yes
NO_JS_CODE=yes
include ../../Makefile.common
