#!/bin/sh -ex
# compile and deploy onto test machine

V=$1
if [ -z "$V" ]; then
  echo Usage: $0 module 
  exit 1
fi
H=127.0.0.1
P=2222

mir clean $V
mir bx $V
scp -P $P $V/mini-os.gz root@$H:/opt/kernels
ssh -p $P root@$H ./mini
