#!/bin/sh -ex
# compile and deploy onto test machine

V=$1
if [ -z "$V" ]; then
  echo Usage: $0 module 
  exit 1
fi
H=127.0.0.1
P=2222
K=/opt/kernels/anil-os.gz
U="a3289cac-d8c1-d26b-4431-30b0d4085394"
mir clean $V
mir bx $V
scp -P $P $V/mini-os.gz root@$H:
ssh -p $P root@$H ./mini
