#!/bin/bash -e
# Run and profile a Mirage app under a Linux domU
# Assumes the file is under test/$1

PROFILING=1
MIRAGE_ROOT=${MIRAGE_ROOT:-`pwd`}
export MIRAGE_ROOT
CONF=${MIRAGE_ROOT}/scripts/linux-config.in
XM_BIN=${XM_BIN:-xm}
MIR_BIN=${MIR_BIN:-mir}
SUDO=${SUDO:-sudo}
XEN_SYMS=${XEN_SYMS:-/boot/xen-syms-3.4.3-rc1-rc1-pre}
GUEST_ROOT=/dev/brolga-0/guest1
NAME=$1
shift

FULLDIR=${MIRAGE_ROOT}/tests/${NAME}
if [ ! -d ${FULLDIR} ]; then
  echo $0: ${FULLDIR} not found
  exit 1
fi

TMPCONF=/tmp/${NAME}.xm

sed -e "s/@NAME@/${NAME}/g" -e "s,@KERNEL@,${FULLDIR}/mini-os.gz,g" < ${CONF} > ${TMPCONF}

cd ${MIRAGE_ROOT}
${MIR_BIN} bu ./tests/${NAME}

MNT=/tmp/${NAME}.mnt
${SUDO} mkdir -p ${MNT}
${SUDO} mount ${GUEST_ROOT} ${MNT}
${SUDO} cp ./tests/${NAME}/app ${MNT}/app
${SUDO} umount ${MNT}

${SUDO} ${XM_BIN} create -p ${TMPCONF}

DOMID=$(${SUDO} ${XM_BIN} domid ${NAME})

if [ ${PROFILING} -gt 0 ]; then
  ${SUDO} opcontrol --reset
  ${SUDO} opcontrol --shutdown
  ${SUDO} opcontrol --start-daemon --event=CPU_CLK_UNHALTED:1000000 --xen=/boot/xen-syms-3.4.3-rc1-pre \
    --passive-domains=${DOMID} --passive-images=${FULLDIR}/mini-os --no-vmlinux
  ${SUDO} opcontrol --start
fi

${SUDO} ${XM_BIN} unpause ${DOMID}

echo -n Waiting for domain to terminate
dom_done=0
while [ $dom_done -eq 0 ]; do
  if ${SUDO} ${XM_BIN} list ${DOMID} >/dev/null 2>&1; then
    echo -n .
    sleep 1
  else
    echo done $?
    dom_done=1
  fi
done

if [ ${PROFILING} -gt 0 ]; then
  ${SUDO} opcontrol --stop
  opreport -l | grep domain${DOMID}
fi
