#!/bin/bash -xe
# Initialize LVM volumes for database and journal for guest
# Deletes any existing present ones and zeroes new ones

SUDO=${SUDO:-sudo}
VG=${VG:-brolga-0}
SIZE=64 # in megabytes
DBNAME=guest-db
JONAME=guest-db-journal
DB=$(readlink -f "/dev/${VG}/${DBNAME}")
JO=$(readlink -f "/dev/${VG}/${JONAME}")

if [ -b ${DB} ]; then
  ${SUDO} lvremove -f ${DB}
fi

if [ -b ${JO} ]; then
  ${SUDO} lvremove -f ${JO}
fi

${SUDO} lvcreate -n "${DBNAME}" -Zy -L${SIZE}M ${VG}
${SUDO} lvcreate -n "${JONAME}" -Zy -L${SIZE}M ${VG}
${SUDO} dd if=/dev/zero of=${DB} count=${SIZE} bs=1M
${SUDO} dd if=/dev/zero of=${JO} count=${SIZE} bs=1M
