#!/bin/bash -x
# Initialize LVM volumes for database and journal for guest
# Deletes any existing present ones and zeroes new ones

SUDO=${SUDO:-sudo}
VG=${VG:-brolga-0}
DBNAME=guest-db
JONAME=guest-db-journal
DB=$(readlink -f "/dev/${VG}/${DBNAME}")
JO=$(readlink -f "/dev/${VG}/${JONAME}")

if [ -b ${DB} ]; then
  ${SUDO} lvremove ${DB}
fi

if [ -b ${JO} ]; then
  ${SUDO} lvremove ${JO}
fi

${SUDO} lvcreate -n "${DBNAME}" -Zy -L512M ${VG}
${SUDO} lvcreate -n "${JONAME}" -Zy -L512M ${VG}

