#!/bin/sh -e
# Build a Mirage Xen binary from an OCaml native code

set -e

usage() {
  cat << EOF
Build a Mirage binary from the OCaml compiler output.

Usage: $0 [-h] [-o <file>] [-b <backend>] <object file>

BACKENDS:
  xen-native (default)
  
OPTIONS:
   -o     Output final binary to <file>.
   -b     Mirage backend to use (see BACKENDS above)
   -h     Show this usage message.
EOF
  exit 1
}

link_xen_native() {
  OBJ=$1
  OUTPUT=$2
  LIB=`ocamlfind query mirage`

  ld -d -nostdlib -m elf_x86_64 -T ${LIB}/mirage-x86_64.lds \
    ${LIB}/x86_64.o ${OBJ} ${LIB}/libocaml.a ${LIB}/libxen.a \
    ${LIB}/libxencaml.a ${LIB}/libdiet.a ${LIB}/libm.a ${LIB}/longjmp.o -o $2
}

BACKEND=xen-native
while [ $# -gt 0 ]; do
  case "$1" in
  -b)
    shift
    BACKEND=$1
    ;;
  -o)
    shift
    OUTPUT="$1"
    ;;
  -h)
    usage
    ;;
  *)
    OBJFILE="$1"
    ;;
  esac
  shift
done

if [ "${OBJFILE}" = "" ]; then
  usage
fi

case "$BACKEND" in
"xen-native")
  link_xen_native ${OBJFILE} ${OUTPUT}
  ;;
*)
  echo Unknown backend $BACKEND
  exit 1
  ;;
esac
