#!/usr/bin/env bash
#
# Build and install all the supported variants of Mirage in fresh
# OPAM switches.  This assumes you have a 4.00.1 system compiler
# (so that fast switching works) and a functional OPAM.
#

# Set your desired pinning here for the core repos

OPAM_REPO=git://github.com/mirage/opam-repository
PIN_MIRAGE_PLATFORM=git://github.com/mirage/mirage-platform
PIN_MIRAGE_NET=git://github.com/mirage/mirage-net
PIN_MIRARI=git://github.com/mirage/mirari
TARGET_PACKAGE="mirage-www"
OPAM=opam
DRY=
#uncomment this if you want a dry run
#DRY=echo

set -e
BASESWITCH=`pwd`
export OPAMROOT="$BASESWITCH/opamroot"
export OPAMYES="doitjustdooooitdooooitnowwww"

$DRY $OPAM init $OPAM_REPO

function pin_if_needed {
  if [ "$2" != "" ]; then
    $DRY $OPAM pin $1 $2
  fi
}
 
function prep_build {
  name=$1
  echo Preparing: $1
  $DRY $OPAM switch $1 -a system
  pin_if_needed mirari "$PIN_MIRARI"
  pin_if_needed mirage-unix "$PIN_MIRAGE_PLATFORM"
  pin_if_needed mirage-xen "$PIN_MIRAGE_PLATFORM"
  pin_if_needed mirage-net-direct "$PIN_MIRAGE_NET"
  pin_if_needed mirage-net-socket "$PIN_MIRAGE_NET"
}

function run_build {
  log="$1.log"
  switch="$2 $3"
  $DRY $OPAM install --switch $1 $2 $3 $TARGET_PACKAGE > $log 2>&1
}

OS=`uname -s`

if [ "$OS" = "Linux" ]; then
  prep_build "xen"
fi
prep_build "unix-direct"
prep_build "unix-socket"

if [ "$OS" = "Linux" ]; then
  run_build "xen" mirage-xen &
fi
run_build "unix-direct" mirage-unix mirage-net-direct &
run_build "unix-socket" mirage-unix mirage-net-socket &
wait
