#!/bin/bash -xe
# Initialize blktap volumes for database and journal for guest
# Deletes any existing present ones and zeroes new ones

SUDO=${SUDO:-sudo}
SIZE=32 # in megabytes
DIR=/root
DBNAME=guest-db
JONAME=guest-db-journal

DB=${DIR}/${DBNAME}
JO=${DIR}/${JONAME}

${SUDO} rm -f ${DB} ${JO}
${SUDO} dd if=/dev/zero of=${DB} count=${SIZE} bs=1M
${SUDO} dd if=/dev/zero of=${JO} count=${SIZE} bs=1M
