ROOTDIR=../../../..
include $(ROOTDIR)/mk/ocaml.mk

DEPENDS=lwt os/unix net/mpl net/api
TARGET=os_device
SOURCES=ethif.ml flow.ml

WITH_SYNTAX=yes
NO_JS_CODE=yes
USE_PACK=yes
include ../../../Makefile.common
