.TH diet 1 "April 2001"
.SH NAME
.PP
diet \- mangle gcc command line arguments
.SH SYNOPSIS
.PP
.B diet [-v] [-Os]
[\fInormal gcc command line\fP]
.SH DESCRIPTION
.PP
diet is a small wrapper around gcc.  It will try to look at the command
line you specify and try to mangle it so that gcc will compile against
the diet libc header files and link against the diet libc itself.

diet tries to be smart for cross compiling.  If the first argument is
not gcc but sparc-linux-gcc, diet will guess that you want to cross
compile for sparc and use bin-sparc/dietlibc.a instead of the dietlibc.a
for your default architecture.

The -v option will make diet print the modified gcc command line before
executing it.

When passed the -Os option before the gcc argument, diet will mangle the
gcc options to include the best known for-size optimization settings for
the platform.
.SH FILES
~/.diet/\fIcompiler\fR may contain compiler options as you would
specify them on the command line, i.e. separated by spaces.  Those will
then be used instead of the built-in defaults for diet -Os.
.SH AUTHOR
Felix von Leitner <felix-dietlibc@fefe.de>
