#########################################################################
#                                                                       #
#                            Objective Caml                             #
#                                                                       #
#            Xavier Leroy, projet Cristal, INRIA Rocquencourt           #
#                                                                       #
#   Copyright 1999 Institut National de Recherche en Informatique et    #
#   en Automatique.  All rights reserved.  This file is distributed     #
#   under the terms of the GNU Library General Public License, with     #
#   the special exception on linking described in file ../../LICENSE.   #
#                                                                       #
#########################################################################

# $Id: Makefile.nt 8477 2007-11-06 15:16:56Z frisch $

# Makefile for the str library

LIBNAME=str
COBJS=strstubs.$(O)
CAMLOBJS=str.cmo

include ../Makefile.nt

depend:

str.cmo: str.cmi 
str.cmx: str.cmi 
