.PHONY: all
all:
	cd native && $(MAKE)
	cd js && $(MAKE)
	cd lwt && $(MAKE)

.PHONY: clean
clean:
	cd native && $(MAKE) clean
	cd js && $(MAKE) clean
	cd lwt && $(MAKE) clean
	

.PHONY: install
install:
	@ :
